POST http://localhost:4003/products
Content-Type: application/json

{
    "name": "Geladinho",
    "price": 1.50
}

###

GET http://localhost:4003/products/

###

PUT http://localhost:4003/products/fd284f
Content-Type: application/json

{
    "name": "Picolé Recheado",
    "price": 3.00
}

###

DELETE http://localhost:4003/products/04009c